---
- name: installing openmrs
  hosts: all
  become: yes
  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /var/lib/OpenMRS
        state: directory
    - name: Recursively change ownership of a directory
      ansible.builtin.command: chown -R tomcat:tomcat /var/lib/OpenMRS
    - name: Download openmrs.war
      ansible.builtin.get_url:
        url: https://sourceforge.net/projects/openmrs/files/releases/OpenMRS_Platform_2.5.0/openmrs.war
        dest: /home/jaya/mine/openmrs
        mode: '777'   
    - name: coping war file
      ansible.builtin.copy:
        src: /home/jaya/mine/openmrs/openmrs.war
        dest: /opt/tomcat/webapps/
    - name: Change ownership of openmrs.war file
      ansible.builtin.file:
        path: /opt/tomcat/webapps/openmrs.war
        owner: tomcat
        group: tomcat
        recurse: yes

        