--- 
- name: tomcat installtion on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: java installtion
      ansible.builtin.apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: creating tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create tomcat user
      ansible.builtin.user: 
        name: tomcat
        group: tomcat
        shell: /bin/false
        home: /opt/tomcat
        state: present
    - name: unarchive tomcat
      ansible.builtin.unarchive:
        src: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.109/bin/apache-tomcat-7.0.109.tar.gz 
        remote_src: yes
        dest: /opt/tomcat/
    - name: create a symbolic link
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.0.27
        dest: /opt/tomcat/latest
        recurse: no
        owner: tomcat
        group: tomcat
        state: link
    - name: changing permissions to file
      ansible.builtin.file:
        dest: /opt/tomcat
        owner: tomcat
        group: tomcat
        state: directory
        mode: '0777'
        recurse: yes
    - name: adding executive permissions to files
      ansible.builtin.command: 
        become: yes
        cmd:
          - chgrp -R tomcat /opt/tomcat
          - chmod -R g+r conf
          - chmod g+x conf
          - chown -R tomcat webapps/ work/ temp/ logs/
    - name: Create a systemd unit file
      ansible.builtin.copy:
        src: tomcat7.service
        dest: /etc/systemd/system/tomcat.service
        owner: tomcat
        group: tomcat
    - name: reload deamon        
      ansible.builtin.systemd:
        daemon_reload: true    
    - name: start tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        enabled: yes
        state: started