---
- name: java installation
  hosts: all
  become: yes
  tasks:
    - name: installing java
      ansible.builtin.apt:
        name: "{{ java_package_name }}"
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"    
    - name: installing java
      ansible.builtin.yum:
        name: "{{ java_package_name }}"
        update_cache: yes
        state: present   
      when: ansible_facts['distribution'] == "CentOS"     